spring.application.name=codelens

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5433/codelens
spring.datasource.username=bashar
spring.datasource.password=codelens
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret=7134743777217A25432A462D4A614E645267556B58703273357638792F423F45
jwt.expiration=86400000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

codelens.cleanup.cron=0 */2 * * * *

codelens.upload.path=uploads

gemini.api-key=${GEMINI_API_KEY}
gemini.api-url=https://generativelanguage.googleapis.com/v1beta/models
gemini.model.text=gemini-2.5-flash
gemini.rate-limit.delay-ms=7000
gemini.rate-limit.max-retries=5


jina.api-key=${JINA_API_KEY}
jina.api-url=https://api.jina.ai/v1/embeddings
jina.embedding-model=jina-embeddings-v3

server.port=8081